apiVersion: v1
kind: Service
metadata:
  name: my-docker-app-service
spec:
  selector:
    app: my-docker-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # On Docker Desktop, this often means a NodePort or will be handled by Docker Desktop's built-in load balancer.